"""Render the dependency-free local Trace explorer."""

from __future__ import annotations

import json


def render_trace_explorer(*, api_base: str = "/api/v1") -> str:
    """Return the self-contained Trace explorer HTML."""
    return _HTML.replace("__API_BASE__", json.dumps(api_base))


_HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>TELOS Traces · 轨迹观测</title>
  <style>
    :root{color-scheme:dark;--bg:#0b0d12;--panel:#11151d;--line:#252b38;--muted:#8d96a8;--text:#edf1f7;--blue:#6aa6ff;--green:#47c78b;--red:#ff6b78;--amber:#efb64b}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:13px/1.45 ui-sans-serif,system-ui,-apple-system,sans-serif}button,input,select{font:inherit;color:inherit}button{cursor:pointer}
    header{height:52px;display:flex;align-items:center;gap:18px;padding:0 18px;border-bottom:1px solid var(--line);background:#0e1118}header b{letter-spacing:.08em}.nav{color:var(--blue);text-decoration:none}.grow{flex:1}.muted{color:var(--muted)}
    .filters{display:flex;gap:8px;padding:10px 12px;border-bottom:1px solid var(--line);background:var(--panel)}input,select{height:32px;border:1px solid var(--line);border-radius:6px;background:#0c1017;padding:0 9px}input{min-width:220px}.filters button,.tab{border:1px solid var(--line);border-radius:6px;background:#161b25;padding:6px 10px}
    main{display:grid;grid-template-columns:minmax(420px,42%) 1fr;height:calc(100vh - 105px)}.list{overflow:auto;border-right:1px solid var(--line)}.detail{overflow:auto}.empty{padding:40px;color:var(--muted);text-align:center}
    .thead,.trace-row{display:grid;grid-template-columns:minmax(150px,1.6fr) 90px 80px 72px 70px 70px 105px;gap:10px;align-items:center;padding:9px 12px}.thead{position:sticky;top:0;background:#0e121a;color:var(--muted);border-bottom:1px solid var(--line);z-index:2}.trace-row{width:100%;border:0;border-bottom:1px solid #1d2330;background:transparent;text-align:left}.trace-row:hover,.trace-row.active{background:#171d28}.trace-name{min-width:0;overflow:hidden}.trace-name b,.trace-name small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.trace-name small{color:var(--muted);font-size:10px}.pill{display:inline-block;width:max-content;padding:2px 7px;border-radius:99px;background:#252c3a;color:#cad2df}.ok{color:var(--green)}.error{color:var(--red)}.running{color:var(--blue)}.cancelled,.abandoned,.unknown{color:var(--amber)}
    .detail-head{padding:16px 18px;border-bottom:1px solid var(--line)}.detail-head h2{font-size:18px;margin:0 0 6px}.metrics{display:flex;gap:20px;margin-top:12px}.metric span{display:block;color:var(--muted);font-size:11px}.metric b{font-size:14px}
    .split{display:grid;grid-template-columns:minmax(300px,46%) 1fr;min-height:520px}.spans{border-right:1px solid var(--line);overflow:auto}.span-head{display:grid;grid-template-columns:1fr 46%;padding:9px 12px;color:var(--muted);border-bottom:1px solid var(--line)}.span-row{display:grid;grid-template-columns:1fr 46%;gap:8px;width:100%;padding:8px 12px;border:0;border-bottom:1px solid #1b202b;background:transparent;text-align:left}.span-row:hover,.span-row.active{background:#171d28}.span-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.barbox{position:relative;height:17px;background:#0b0e14;border-radius:3px}.bar{position:absolute;top:4px;height:9px;min-width:2px;border-radius:3px;background:var(--blue)}.bar.tool{background:#b17df5}.bar.llm{background:var(--green)}.bar.error{background:var(--red)}
    .inspect{min-width:0}.tabs{display:flex;gap:6px;padding:10px;border-bottom:1px solid var(--line)}.tab.active{border-color:var(--blue);color:var(--blue)}pre{margin:0;padding:14px;white-space:pre-wrap;overflow-wrap:anywhere;color:#dce3ed;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.timeline,.feedback{padding:12px;border-top:1px solid var(--line)}.timeline h3{margin:0 0 8px;font-size:12px;color:var(--muted)}.timeline button{display:block;width:100%;padding:6px 8px;border:0;border-radius:4px;background:transparent;text-align:left}.timeline button:hover{background:#171d28}.feedback input{min-width:90px;width:90px}.feedback button,.load-more{height:32px;border:0;border-radius:6px;background:var(--blue);color:#08101d;padding:0 12px;font-weight:700}.load-wrap{text-align:center;padding:12px}
    @media(max-width:900px){main{grid-template-columns:1fr}.list{border-right:0}.detail{display:none}.detail.open{display:block;position:fixed;inset:52px 0 0;background:var(--bg);z-index:4}.split{grid-template-columns:1fr}.spans{border-right:0}.thead,.trace-row{grid-template-columns:1fr 75px 70px}.optional{display:none}}
    :root{color-scheme:light;--bg:#f6f7fb;--panel:#fff;--line:#e2e5ec;--muted:#687083;--text:#20222b;--blue:#5b5bd6;--green:#158a62;--red:#d4475f;--amber:#a8660d}
    .shell{display:grid;grid-template-columns:232px minmax(0,1fr);min-height:100vh}.side{height:100vh;position:sticky;top:0;padding:20px 14px;border-right:1px solid var(--line);background:#fbfbfd;display:flex;flex-direction:column}.brand{padding:3px 10px 19px;font-size:16px;font-weight:800;letter-spacing:.08em}.brand i{display:inline-grid;place-items:center;width:27px;height:27px;margin-right:9px;border-radius:7px;background:var(--blue);color:#fff;font-style:normal;letter-spacing:0}.workspace-pill{margin:0 6px 18px;padding:10px 11px;border:1px solid var(--line);border-radius:9px;background:#fff}.workspace-pill small{display:block;color:var(--muted);font-size:11px}.side nav{display:grid;gap:3px}.nav-label{padding:18px 10px 6px;color:#9299a8;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.1em}.side nav a{display:flex;gap:9px;padding:9px 10px;border-radius:7px;color:#51586a;text-decoration:none}.side nav a:hover{background:#f0f1f6}.side nav a.active{background:#ececff;color:var(--blue);font-weight:650}.nav-icon{width:17px;text-align:center}.side-foot{margin-top:auto;padding:10px;color:var(--muted);font-size:12px}.content{min-width:0}
    header{height:52px;background:#ffffffdc;padding:0 20px}.filters{background:#fff;padding:10px 12px}input,select{background:#fff}.filters button,.tab{background:#f8f9fc}.thead{background:#f8f9fc}.trace-row{border-bottom-color:#eef0f4}.trace-row:hover,.trace-row.active,.span-row:hover,.span-row.active,.timeline button:hover{background:#f3f3ff}.pill{background:#eff0f4;color:#51586a}.barbox{background:#f0f1f5}.detail-head{background:#fff}.span-row{border-bottom-color:#eef0f4}pre{color:#3e4554}.load-more,.feedback button{color:#fff}
    @media(max-width:900px){.shell{grid-template-columns:72px minmax(0,1fr)}.side{padding:18px 8px}.brand{font-size:0;padding:3px 13px 18px}.brand i{margin:0}.workspace-pill,.nav-label,.side nav a span:not(.nav-icon),.side-foot{display:none}.side nav a{justify-content:center}.detail.open{inset:52px 0 0 72px}}
  </style>
</head>
<body>
<div class="shell"><aside class="side"><div class="brand"><i>T</i>TELOS</div><div class="workspace-pill"><small>Workspace</small><strong>Local agent lab</strong></div><nav><div class="nav-label">工作台</div><a href="/"><span class="nav-icon">⌂</span><span>首页</span></a><a href="/runs"><span class="nav-icon">≡</span><span>多任务</span></a><div class="nav-label">观测与评估</div><a class="active" href="/traces"><span class="nav-icon">⌁</span><span>轨迹观测</span></a><a href="/evaluations"><span class="nav-icon">↗</span><span>评估中心</span></a><div class="nav-label">系统</div><a href="/savings"><span class="nav-icon">◫</span><span>节省分析</span></a><a href="/developer"><span class="nav-icon">⌘</span><span>开发者</span></a></nav><div class="side-foot">Portable context.<br>Immutable evidence.</div></aside><div class="content">
<header><b>轨迹观测</b><span class="muted">逐步检查模型请求、工具调用、Token、成本与失败原因</span><span class="grow"></span><span id="health" class="muted">connecting…</span></header>
<div class="filters">
  <input id="search" type="search" placeholder="搜索轨迹、输入或输出" aria-label="搜索轨迹">
  <select id="project" aria-label="项目"><option value="">全部项目</option></select>
  <select id="harness" aria-label="Runtime"><option value="">全部 runtime</option><option>codex</option><option>kimi-code</option><option>deepseek-harness</option></select>
  <select id="status" aria-label="状态"><option value="">全部状态</option><option>running</option><option>ok</option><option>error</option><option>cancelled</option><option>abandoned</option><option>unknown</option></select>
  <input id="model" placeholder="模型" aria-label="模型">
  <input id="from" type="datetime-local" aria-label="Started after">
  <input id="to" type="datetime-local" aria-label="Started before">
  <button id="refresh">刷新</button>
</div>
<main><section class="list"><div class="thead"><span>轨迹</span><span>Runtime</span><span>状态</span><span class="optional">耗时</span><span class="optional">Tokens</span><span class="optional">成本</span><span>开始时间</span></div><div id="rows"></div><div id="list-empty" class="empty">还没有轨迹</div><div class="load-wrap"><button id="load-more" class="load-more" hidden>加载更多</button></div></section><section id="detail" class="detail"><div class="empty">选择一条轨迹查看 Span 瀑布图</div></section></main></div></div>
<script type="module">
const API=__API_BASE__, $=s=>document.querySelector(s), initialAttempt=new URLSearchParams(location.search).get('attempt_id'); let selectedId=null, selectedSpan=null, selectedInspectorTab='Input', currentDetail=null, nextCursor=null;
const escTime=us=>us?new Date(us/1000).toLocaleString():'—';
const duration=(a,b)=>{if(!a)return '—';const ms=((b||Date.now()*1000)-a)/1000;return ms<1000?Math.round(ms)+' ms':(ms/1000).toFixed(2)+' s'};
const tokens=t=>(t??0).toLocaleString(); const money=m=>m==null?'—':'$'+(m/1e6).toFixed(4);
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n}
function query(cursor){const p=new URLSearchParams({limit:'100'});if(initialAttempt)p.set('attempt_id',initialAttempt);for(const id of ['search','project','harness','status','model']){const v=$('#'+id).value.trim();if(v)p.set(id==='search'?'q':id==='project'?'project_id':id,v)}for(const [id,key] of [['from','start_time_from_us'],['to','start_time_to_us']]){const v=$('#'+id).value;if(v)p.set(key,String(Date.parse(v)*1000))}if(cursor)p.set('cursor',cursor);return p}
async function loadProjects(){const r=await fetch(`${API}/projects`);if(!r.ok)return;for(const p of (await r.json()).items||[]){const o=el('option','',p.name);o.value=p.id;$('#project').append(o)}}
async function loadList(append=false){try{const r=await fetch(`${API}/traces?${query(append?nextCursor:null)}`);if(!r.ok)throw Error(await r.text());const data=await r.json();renderRows(data.items||[],append);nextCursor=data.next_cursor||null;$('#load-more').hidden=!nextCursor;$('#health').textContent='live · '+new Date().toLocaleTimeString()}catch(e){$('#health').textContent='offline';if(!append)$('#rows').replaceChildren(el('div','empty',String(e)))} }
function renderRows(items,append){const root=$('#rows');if(!append)root.replaceChildren();$('#list-empty').hidden=root.childElementCount+items.length>0;for(const t of items){const b=el('button','trace-row'+(t.id===selectedId?' active':''));b.dataset.id=t.id;const name=el('span','trace-name');name.append(el('b','',t.name||'Untitled trace'),el('small','',t.task_name?`Long Task · ${t.task_name}`:t.attempt_id?'TaskRun evidence':'Unassigned evidence'));b.append(name,el('span','pill',t.harness||'unknown'),el('span',t.status||'unknown',t.status||'unknown'),el('span','optional',duration(t.start_time_us,t.end_time_us)),el('span','optional',tokens(t.total_tokens)),el('span','optional',money(t.cost_usd_micros)),el('span','',escTime(t.start_time_us)));b.onclick=()=>loadDetail(t.id);root.append(b)}}
async function loadDetail(id){selectedId=id;selectedSpan=null;document.querySelectorAll('.trace-row').forEach(n=>n.classList.toggle('active',n.dataset.id===id));const r=await fetch(`${API}/traces/${encodeURIComponent(id)}`);if(!r.ok){$('#detail').replaceChildren(el('div','empty',await r.text()));return}currentDetail=await r.json();const threadId=currentDetail.trace?.thread_id;if(threadId){const tr=await fetch(`${API}/threads/${encodeURIComponent(threadId)}`);if(tr.ok)currentDetail.thread_detail=await tr.json()}renderDetail(currentDetail);$('#detail').classList.add('open')}
function renderDetail(data){const t=data.trace||data, spans=data.spans||[];const root=$('#detail');root.replaceChildren();const head=el('div','detail-head');const title=el('h2','',t.name||'Untitled trace');const owner=data.task?`Long Task: ${data.task.name} · Execution ${String(data.task_execution?.id||'').slice(0,8)} · Attempt ${String(data.attempt?.id||'').slice(0,8)}`:data.task_run?`TaskRun: ${data.task_run.goal} · Attempt ${String(data.attempt?.id||'').slice(0,8)}`:'Unassigned evidence · no Task/Attempt link';const sub=el('div','muted',`${t.harness||'unknown'} · ${t.status||'unknown'} · ${escTime(t.start_time_us)} · ${owner}`);const metrics=el('div','metrics');for(const [k,v] of [['Duration',duration(t.start_time_us,t.end_time_us)],['Tokens',tokens(t.total_tokens)],['Cost',money(t.cost_usd_micros)],['Spans',String(spans.length)]]){const m=el('div','metric');m.append(el('span','',k),el('b','',v));metrics.append(m)}head.append(title,sub,metrics);const split=el('div','split');const tree=el('div','spans');const sh=el('div','span-head');sh.append(el('span','','Span'),el('span','','Timeline'));tree.append(sh);renderSpans(tree,spans,t);const inspect=el('div','inspect');renderInspector(inspect,t);split.append(tree,inspect);root.append(head,split);const timeline=el('section','timeline');timeline.append(el('h3','','Thread timeline'));for(const trace of data.thread_detail?.traces||[]){const b=el('button','',`${escTime(trace.start_time_us)} · ${trace.status} · ${trace.name}`);b.type='button';b.onclick=()=>loadDetail(trace.id);timeline.append(b)}root.append(timeline);const fb=el('form','feedback');const label=el('span','muted','Score ');const input=el('input');input.type='number';input.name='value';input.step='any';input.required=true;input.setAttribute('aria-label','Feedback score');const name=el('input');name.name='name';name.placeholder='quality';name.value='quality';name.setAttribute('aria-label','Feedback name');const submit=el('button','','Save feedback');fb.append(label,input,name,submit);fb.onsubmit=async e=>{e.preventDefault();await fetch(`${API}/feedback-scores`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trace_id:t.id,name:name.value,value:Number(input.value)})});input.value=''};root.append(fb)}
function renderSpans(root,spans,trace){const byParent=new Map();for(const s of spans){const p=s.parent_span_id||'';if(!byParent.has(p))byParent.set(p,[]);byParent.get(p).push(s)}for(const a of byParent.values())a.sort((x,y)=>x.start_time_us-y.start_time_us);const traceEnd=trace.end_time_us||Date.now()*1000,total=Math.max(1,traceEnd-trace.start_time_us);const seen=new Set();function walk(parent,depth){for(const s of byParent.get(parent)||[]){if(seen.has(s.id))continue;seen.add(s.id);const row=el('button','span-row');const label=el('span','span-label',`${'  '.repeat(depth)}${s.name||s.type}`);const box=el('span','barbox');const bar=el('span',`bar ${s.type||''} ${s.status==='error'?'error':''}`);bar.style.left=Math.max(0,(s.start_time_us-trace.start_time_us)/total*100)+'%';bar.style.width=Math.max(.5,((s.end_time_us||traceEnd)-s.start_time_us)/total*100)+'%';box.append(bar);row.append(label,box);row.onclick=()=>{selectedSpan=s;document.querySelectorAll('.span-row').forEach(n=>n.classList.remove('active'));row.classList.add('active');renderInspector(root.parentElement.querySelector('.inspect'),s)};root.append(row);walk(s.id,depth+1)}}walk('',0);for(const s of spans)if(!seen.has(s.id)){const copy={...s,parent_span_id:null};if(!byParent.has(''))byParent.set('',[]);byParent.get('').push(copy)}walk('',0) }
function renderInspector(root,item){root.replaceChildren();const tabs=el('div','tabs');const pre=el('pre');const values={Input:item.input_json??item.input,Output:item.output_json??item.output,Metadata:item.metadata_json??item.metadata,Usage:item.usage_json??item.usage,Error:item.error_json??item.error};function show(k,b){selectedInspectorTab=k;tabs.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=values[k];if(typeof v==='string'){try{v=JSON.parse(v)}catch{}}pre.textContent=v==null?'No data':typeof v==='string'?v:JSON.stringify(v,null,2)}for(const k of Object.keys(values)){const b=el('button','tab',k);b.type='button';b.onclick=()=>show(k,b);tabs.append(b)}root.append(tabs,pre);show(selectedInspectorTab,[...tabs.children].find(b=>b.textContent===selectedInspectorTab)||tabs.firstChild)}
let debounce;for(const id of ['search','project','harness','status','model','from','to'])$('#'+id).addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(()=>loadList(false),180)});$('#refresh').onclick=()=>loadList(false);$('#load-more').onclick=()=>loadList(true);loadProjects();loadList(false);setInterval(()=>{loadList(false);if(selectedId)loadDetail(selectedId)},2000);
</script>
</body></html>'''


if __name__ == "__main__":
    print(render_trace_explorer())
