"""Render the local Context Control Plane without a frontend build step."""

from __future__ import annotations

import json


def render_context_control(write_token: str) -> str:
    token = json.dumps(write_token)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TELOS · Context Control Plane</title>
<style>
:root{{--bg:#070a0f;--panel:#0d121a;--panel2:#121925;--line:#263142;--text:#edf3ff;--muted:#8e9aab;--blue:#61a5ff;--green:#52d6a0;--amber:#f0bb62;--red:#ff7185}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 ui-sans-serif,system-ui,-apple-system,sans-serif}}
header{{height:64px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 28px;gap:30px;position:sticky;top:0;background:#070a0fee;backdrop-filter:blur(12px);z-index:3}}
.brand{{font-weight:800;letter-spacing:.16em}}.brand span{{color:var(--blue)}}nav{{display:flex;gap:5px;height:100%;align-items:center}}
nav button,nav a{{border:0;background:transparent;color:var(--muted);padding:20px 15px;text-decoration:none;font:inherit;cursor:pointer;border-bottom:2px solid transparent}}
nav button.active{{color:var(--text);border-color:var(--blue)}}.spacer{{flex:1}}.live{{color:var(--green);font-size:12px}}
main{{max-width:1440px;margin:auto;padding:28px}}.eyebrow{{font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:var(--muted)}}
h1{{font-size:25px;margin:6px 0 4px}}h2{{font-size:15px;margin:0}}p{{margin:6px 0;color:var(--muted)}}
.hero{{display:flex;align-items:flex-end;gap:24px;margin-bottom:22px}}.hero .actions{{margin-left:auto;display:flex;gap:9px}}
button.action,select{{border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:8px;padding:9px 12px}}
button.action{{cursor:pointer}}button.action.primary{{background:var(--blue);color:#06101d;border-color:var(--blue);font-weight:700}}button:disabled{{opacity:.45;cursor:not-allowed}}
.grid{{display:grid;grid-template-columns:1.05fr 1.55fr 1fr;gap:14px}}.card{{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:17px;min-width:0}}
.cardhead{{display:flex;align-items:center;justify-content:space-between;margin-bottom:15px}}.digest{{font:11px ui-monospace,monospace;color:var(--muted)}}
.status{{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line);border-radius:99px;padding:4px 8px;font-size:11px}}.dot{{width:7px;height:7px;border-radius:50%;background:currentColor}}
.native,.ok,.complete,.production,.recommended,.passed{{color:var(--green)}}.degraded,.dirty,.partial,.evaluating,.running{{color:var(--amber)}}.blocked,.invalid,.error,.failed,.rejected{{color:var(--red)}}
.layers{{display:grid;gap:8px}}.layer{{display:flex;align-items:center;padding:9px 10px;background:var(--panel2);border-radius:8px}}.layer b{{text-transform:capitalize}}.layer span{{margin-left:auto;color:var(--green)}}
.lineage{{display:flex;align-items:center;gap:8px;overflow:auto;padding:5px 1px 12px}}.attempt{{min-width:155px;padding:13px;border:1px solid var(--line);border-radius:9px;background:var(--panel2)}}
.attempt strong{{display:block;margin-bottom:5px}}.arrow{{color:var(--blue);font-size:18px}}.small{{font-size:12px;color:var(--muted)}}
.matrix{{display:grid;gap:8px}}.matrixrow{{display:grid;grid-template-columns:1fr auto;gap:8px;padding:9px 10px;background:var(--panel2);border-radius:8px}}.matrixrow small{{grid-column:1/-1;color:var(--muted)}}
.wide{{grid-column:1/-1}}.gates{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}}.gate{{padding:10px;background:var(--panel2);border-radius:8px;border-left:3px solid currentColor}}
.empty{{padding:30px;text-align:center;color:var(--muted)}}.view{{display:none}}.view.active{{display:block}}.notice{{border:1px solid var(--line);padding:11px 13px;border-radius:8px;margin-bottom:14px;color:var(--muted)}}
.diff{{white-space:pre-wrap;overflow:auto;max-height:280px;background:#070a0f;border-radius:8px;padding:12px;color:#cbd5e6;font:12px/1.5 ui-monospace,monospace}}
dialog{{background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:12px;max-width:650px;width:calc(100% - 40px)}}dialog::backdrop{{background:#000a}}.dialog-actions{{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}}
@media(max-width:950px){{.grid{{grid-template-columns:1fr}}.wide{{grid-column:auto}}.gates{{grid-template-columns:1fr 1fr}}header{{padding:0 14px;gap:10px}}nav button,nav a{{padding:20px 8px}}main{{padding:18px}}}}
</style></head><body>
<header><div class="brand"><span>TELOS</span> CONTROL</div><nav>
<button data-view="context">Context</button><button data-view="runs">Runs</button><button data-view="evolution">Evolution</button><a href="/__telos/traces">Evidence ↗</a>
</nav><div class="spacer"></div><div class="live">● local only</div></header>
<main>
<section id="context" class="view"><div id="contextContent" class="empty">Loading context…</div></section>
<section id="runs" class="view"><div class="hero"><div><div class="eyebrow">Execution lineage</div><h1>TaskRuns across Harnesses</h1><p>Every handoff creates a new Attempt; history is never rewritten.</p></div></div><div id="runsContent" class="empty">Loading runs…</div></section>
<section id="evolution" class="view"><div class="hero"><div><div class="eyebrow">Offline learning loop</div><h1>Profile evolution</h1><p>Frozen evidence → single-dimension Candidate → cross-Harness gates → manual release.</p></div></div><div id="evolutionContent" class="empty">Loading evolution…</div></section>
</main>
<dialog id="handoffDialog"><h2>Handoff compatibility</h2><div id="handoffReport"></div><div class="dialog-actions"><button class="action" id="cancelHandoff">Cancel</button><button class="action primary" id="confirmHandoff">Create destination Attempt</button></div></dialog>
<script type="module">
const TOKEN={token};
const state={{runs:[],selectedRun:null,detail:null,pack:null,evolution:null,destination:'kimi-code'}};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
const short=value=>value?esc(String(value).slice(0,8)):'none';
const badge=value=>`<span class="status ${{esc(value)}}"><i class="dot"></i>${{esc(value)}}</span>`;
async function api(path,options={{}}){{const response=await fetch('/__telos/api/v1'+path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${{response.status}}`);return data}}
function setView(view){{if(!['context','runs','evolution'].includes(view))view='context';document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));localStorage.setItem('telos.control.view',view);location.hash=view}}
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>setView(button.dataset.view));setView(location.hash.slice(1)||localStorage.getItem('telos.control.view')||'context');
function attemptCard(a){{const traces=(state.detail?.traces||[]).filter(t=>t.attempt_id===a.id);return `<div class="attempt"><strong>${{esc(a.harness)}}</strong>${{badge(a.status)}}<div class="small">Attempt ${{short(a.id)}}</div>${{a.profile_revision_id?`<div class="small">Profile ${{short(a.profile_revision_id)}}</div>`:''}}<div class="small"><a href="/__telos/traces" style="color:var(--blue)">${{traces.length}} evidence trace(s) ↗</a></div></div>`}}
function lineage(detail){{return detail.attempts.length?detail.attempts.map((a,i)=>(i?'<span class="arrow">→</span>':'')+attemptCard(a)).join(''):'<div class="empty">No Attempt yet</div>'}}
function layerRows(pack){{const layers=pack?.manifest?.layers||{{}};return Object.entries(layers).map(([name,value])=>`<div class="layer"><b>${{esc(name)}}</b><span>${{value==='included'?'✓ included':'— omitted'}}</span></div>`).join('')}}
function portability(pack){{const reports=pack?.portability||{{}};return Object.entries(reports).map(([name,report])=>{{const diff=Object.entries(report.layers).filter(([,v])=>v.level!=='native').map(([k,v])=>`${{k}}: ${{v.detail}}`).join(' · ');return `<div class="matrixrow"><strong>${{esc(name)}}</strong>${{badge(report.overall)}}<small>${{esc(diff||'All included semantic layers are expressible natively.')}}</small></div>`}}).join('')||'<div class="empty">Create a Pack to compare Harnesses.</div>'}}
async function load(){{try{{const listed=await api('/task-runs');state.runs=listed.items;if(!state.selectedRun||!state.runs.some(r=>r.id===state.selectedRun))state.selectedRun=state.runs[0]?.id||null;let detail=null;if(state.selectedRun)detail=await api('/task-runs/'+encodeURIComponent(state.selectedRun));state.detail=detail;const latestPack=detail?.packs.at(-1);state.pack=latestPack?await api('/packs/'+encodeURIComponent(latestPack.id)):null;state.evolution=detail?.task_run.task_type_id?await api('/evolution/'+encodeURIComponent(detail.task_run.task_type_id)).catch(()=>null):null;renderContext(detail);renderRuns();renderEvolution()}}catch(error){{document.getElementById('contextContent').innerHTML=`<div class="notice error">${{esc(error.message)}}</div>`}}}}
function renderContext(detail){{const root=document.getElementById('contextContent');if(!detail){{root.innerHTML='<div class="empty"><h2>No TaskRun yet</h2><p>Start with <code>telos pack --attempt &lt;id&gt;</code> from an explicitly linked Harness.</p></div>';return}}const run=detail.task_run,latest=detail.attempts.at(-1),pack=state.pack;root.innerHTML=`
<div class="hero"><div><div class="eyebrow">Current TaskRun ${{short(run.id)}}</div><h1>${{esc(run.goal)}}</h1><p>${{latest?`Now continuing in ${{esc(latest.harness)}} · Attempt ${{short(latest.id)}}`:'No active Attempt'}}</p></div><div class="actions"><button class="action" id="capturePack" ${{latest?'':'disabled'}}>Checkpoint</button><select id="destination"><option value="kimi-code">Kimi Code</option><option value="codex">Codex</option><option value="deepseek-harness">DeepSeek Harness</option></select><button class="action primary" id="handoff" ${{pack?'':'disabled'}}>Review handoff</button></div></div>
<div class="grid"><article class="card"><div class="cardhead"><h2>Context Pack</h2>${{pack?badge(pack.capture_status):badge('missing')}}</div>${{pack?`<div class="digest">${{esc(pack.digest)}}</div><div class="layers">${{layerRows(pack)}}</div>`:'<div class="empty">No semantic checkpoint for this run.</div>'}}</article>
<article class="card"><div class="cardhead"><h2>Run lineage</h2><span class="small">${{detail.attempts.length}} attempt(s)</span></div><div class="lineage">${{lineage(detail)}}</div><p>Each card is an immutable Harness execution identity. Evidence links below it by Attempt ID.</p></article>
<article class="card"><div class="cardhead"><h2>Portability</h2><span class="small">loss is explicit</span></div><div class="matrix">${{portability(pack)}}</div></article>
<article class="card wide"><div class="cardhead"><h2>Evolution pressure</h2>${{state.evolution?.task_type.production_profile_revision_id?badge('production'):badge('unclassified')}}</div>${{evolutionStrip(state.evolution)}}</article></div>`;
document.getElementById('capturePack')?.addEventListener('click',async()=>{{await write('/packs',{{attempt_id:latest.id,workspace:run.workspace?.root,requirements:run.workspace?.root?{{workspace:'read-write',tools:['shell','file-edit']}}:{{}}}});await load()}});document.getElementById('handoff')?.addEventListener('click',reviewHandoff)}}
function evolutionStrip(data){{if(!data)return '<div class="empty">Assign a TaskType to collect eligible learning evidence.</div>';const current=data.revisions.find(x=>x.id===data.task_type.production_profile_revision_id),candidate=data.revisions.find(x=>['draft','evaluating','recommended'].includes(x.state)),evaluation=data.evaluations[0];return `<div class="lineage"><div class="attempt"><strong>Production</strong><div>${{short(current?.id)}}</div></div><span class="arrow">← evidence →</span><div class="attempt"><strong>Candidate</strong><div>${{candidate?short(candidate.id):'none'}}</div></div><span class="small">${{data.regression_cases.length}} frozen case(s) · ${{evaluation?esc(evaluation.status):'not evaluated'}}</span></div>`}}
function renderRuns(){{const root=document.getElementById('runsContent');root.className='grid';root.innerHTML=state.runs.map(run=>`<article class="card wide" data-run="${{esc(run.id)}}"><div class="cardhead"><div><div class="eyebrow">${{esc(run.task_type_name||'unclassified')}}</div><h2>${{esc(run.goal)}}</h2></div>${{badge(run.status)}}</div><p>${{run.attempt_count}} Attempt(s) · ${{run.pack_count}} Pack(s) · TaskRun ${{short(run.id)}}</p></article>`).join('')||'<div class="empty">No TaskRuns.</div>';root.querySelectorAll('[data-run]').forEach(card=>card.onclick=()=>{{state.selectedRun=card.dataset.run;setView('context');load()}})}}
function renderEvolution(){{const root=document.getElementById('evolutionContent'),data=state.evolution;if(!data){{root.innerHTML='<div class="empty">No classified TaskRun selected.</div>';return}}const evaluation=data.evaluations[0],gates=evaluation?.gates||{{}},candidate=data.revisions.find(r=>r.diff);root.innerHTML=`<div class="grid"><article class="card"><div class="cardhead"><h2>Profile revisions</h2><span>${{data.revisions.length}}</span></div>${{data.revisions.map(r=>`<div class="matrixrow"><strong>${{short(r.id)}} · ${{esc(r.change_dimension||'baseline')}}</strong>${{badge(r.state)}}<small>${{esc(r.digest)}}</small></div>`).join('')}}</article><article class="card"><div class="cardhead"><h2>Frozen evidence</h2><span>${{data.regression_cases.length}}</span></div>${{data.regression_cases.map(c=>`<div class="matrixrow"><strong>${{esc(c.classification||c.outcome)}}</strong>${{c.protected?badge('protected'):badge('case')}}<small>Pack ${{short(c.pack_id)}} · score ${{esc(c.score??'—')}}</small></div>`).join('')||'<div class="empty">No RegressionCase.</div>'}}</article><article class="card"><div class="cardhead"><h2>Latest evaluation</h2>${{evaluation?badge(evaluation.status):badge('not-run')}}</div><p>Reference and Candidate run the same case × Harness matrix.</p><div class="dialog-actions">${{candidate?.state==='recommended'?'<button class="action primary" id="promoteCandidate">Promote Candidate</button>':''}}<button class="action" id="rollbackProfile">Rollback production</button></div></article><article class="card wide"><div class="cardhead"><h2>Candidate diff</h2><span class="small">one change dimension</span></div>${{candidate?`<pre class="diff">${{esc(candidate.diff)}}</pre>`:'<div class="empty">No Candidate diff.</div>'}}</article><article class="card wide"><div class="cardhead"><h2>Quality gates</h2><span class="small">manual promotion only</span></div><div class="gates">${{Object.entries(gates).map(([name,gate])=>`<div class="gate ${{gate.passed?'passed':'failed'}}"><strong>${{esc(name.replaceAll('_',' '))}}</strong><div>${{gate.passed?'passed':'blocked'}}</div></div>`).join('')||'<div class="empty">No evaluation gates yet.</div>'}}</div></article></div>`;document.getElementById('promoteCandidate')?.addEventListener('click',async()=>{{await write(`/profile-revisions/${{candidate.id}}/promote`);await load()}});document.getElementById('rollbackProfile')?.addEventListener('click',async()=>{{await write(`/task-types/${{data.task_type.id}}/rollback`);await load()}})}}
async function write(path,body={{}}){{return api(path,{{method:'POST',headers:{{'Content-Type':'application/json','Authorization':'Bearer '+TOKEN}},body:JSON.stringify(body)}})}}
async function reviewHandoff(){{const destination=document.getElementById('destination').value;state.destination=destination;const dialog=document.getElementById('handoffDialog'),reportRoot=document.getElementById('handoffReport');reportRoot.innerHTML='Checking semantic compatibility…';dialog.showModal();try{{const report=await api('/handoffs/plan',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{pack_id:state.pack.id,destination}})}});reportRoot.innerHTML=`<p>Overall ${{badge(report.overall)}}</p><div class="matrix">${{Object.entries(report.layers).map(([name,item])=>`<div class="matrixrow"><strong>${{esc(name)}}</strong>${{badge(item.level)}}<small>${{esc(item.detail)}}</small></div>`).join('')}}</div>`;document.getElementById('confirmHandoff').disabled=report.overall==='blocked'}}catch(error){{reportRoot.innerHTML=`<p class="error">${{esc(error.message)}}</p>`;document.getElementById('confirmHandoff').disabled=true}}}}
document.getElementById('cancelHandoff').onclick=()=>document.getElementById('handoffDialog').close();document.getElementById('confirmHandoff').onclick=async()=>{{const button=document.getElementById('confirmHandoff');button.disabled=true;try{{const created=await api('/handoffs',{{method:'POST',headers:{{'Content-Type':'application/json','Authorization':'Bearer '+TOKEN}},body:JSON.stringify({{pack_id:state.pack.id,destination:state.destination}})}});document.getElementById('handoffReport').innerHTML=`<div class="notice ok"><strong>Destination Attempt created.</strong><br>Launch from a terminal:<pre class="diff">${{esc(created.plan.command_display)}}</pre></div>`;button.hidden=true;await load()}}catch(error){{document.getElementById('handoffReport').insertAdjacentHTML('afterbegin',`<p class="error">${{esc(error.message)}}</p>`);button.disabled=false}}}};
await load();setInterval(load,5000);
</script></body></html>"""


def main() -> int:
    print(render_context_control("local-preview-token"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
